SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2026 embedded brains GmbH & Co. KG
enabled-by: true
links:
- role: spec-member
  uid: root
spec-description: null
spec-example: null
spec-info:
  list:
    description: |
      It shall be the list of application configuration documentation groups.
    spec-type: tool-appl-config-doc-group
spec-name: Tool Application Configuration Documentation Group List
spec-type: tool-appl-config-doc-group-list
type: spec
