# SPDX-License-Identifier: BSD-2-Clause

# Copyright (C) 2026 embedded brains GmbH & Co. KG

name: Publish to TestPyPI
on:
  push:
    tags:
    - devel/*
jobs:
  publish-to-testpypi:
    name: Publish to TestPyPI
    environment:
      name: testpypi
      url: https://test.pypi.org/p/specware/
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: .python-version
    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        version: 0.10.12
    - name: Make
      run: make dist
    - name: Publish to TestPyPI
      run: uv publish --trusted-publishing always --publish-url https://test.pypi.org/legacy/
